/*
 * generated by Xtext 2.11.0
 */
package it.unige.csec


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class LmetStandaloneSetup extends LmetStandaloneSetupGenerated {

	def static void doSetup() {
		new LmetStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
