/*
 * generated by Xtext 2.11.0
 */
package it.unige.csec.validation

import org.eclipse.xtext.validation.Check
import it.unige.csec.lmet.Program

/**
 * This class contains custom validation rules. 
 *
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
class LmetValidator extends AbstractLmetValidator {
	
	public static val INVALID_NAME = 'invalidName'

	@Check
	def checkProgram(Program p) {
		var vlen = p.table.get(0).vect.size;
		for(d : p.table) {
			if(d.vect.size != vlen) {
				error("Vectors must have the same size", d, null);	
			}
		} 
			
	}
	
}
